version: "3.7"

services:
  mysql-dp:
    image: mysql
    container_name: mysql-dp
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports: 
      - "33016:3306"
    env_file: # Environment Variables list
      - databases/mysql/env_vars.env
    volumes: # At /databases/mysql/dumps are the .sql files to dump
      - ./databases/mysql/dumps:/docker-entrypoint-initdb.d
      - ./databases/mysql/data:/var/lib/mysql
    networks:
      - local-network

  frontend:
    build: ./frontend
    container_name: frontend-dp
    restart: always
    ports:
      - "4200:4200"
    networks:
      - local-network

  register-dp:
    build: ./services/register
    container_name: register-dp
    restart: always
    depends_on:
      - mysql-dp
    ports: 
      - "8000:8000" # REST
    networks: 
      - local-network

networks:
  local-network: